version: '3.4'
services:
  app:
    build:
      context: .
      network: host
    command:  bash -c "./bin/start.sh"
    volumes:
      - .:/usr/src/app
    ports:
      - "3978:3978"
    env_file:
      - compose.env

  cosmos-db:
    image: microsoft/azure-cosmosdb-emulator
